### ISSUE TITLE
network error: HostNotFoundError

### ISSUE THREAD

**Issue by cdanger** [Fiware/tools.Fabre#13]
Hello,
I have the following issue when running fabre:
`Exit with code 1 due to network error: HostNotFoundError`

**Comment by FiwareULPGC** [comment]
Hi!

Are you executing Fabre after installing it or are you using the docker image?

Can you provide us the following information?
-  Operating system.
-  Apib file.
- All console output when you run Fabre.
-  Fabre version. You can get it by executing `fabre --version`

**Comment by cdanger** [comment]
Hello,
I was still using Fabre v0.3.1 apparently. I re-installed Fabre in the current version 0.3.2.1 and it appears the issue has gone away. So I can close the issue. Sorry for the useless trouble.
