### ISSUE TITLE
Metadata required by the tool don't match the ones in Fabre style guide

### ISSUE THREAD

**Issue by cdanger** [Fiware/tools.Fabre#14]
Hello,
the tool (v0.3.2.1) refuses to generate if there is no GITHUB_SOURCE, SPEC_URL, VERSION or APIARY_PROJECT metadata, whereas the [Fabre style guide](https://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/Fabre_style_guide) says there are **optional**. Could you fix one or the other to avoid confusion?

Thanks.

**Comment by FiwareULPGC** [comment]
Hello,

 Please, note that the current version, as specified in this [manual](https://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/Fabre_style_guide#Current_version) is 0.3.1.1.

 Because of the v0.3.2.1 is more restrictive you are getting this error.

Regards

**Comment by cdanger** [comment]
OK so I understandard that v0.3.2.1 is not yet an official release and that we should still use 0.3.1.1. Thanks.
